"use client";

import { useState } from "react";
import type {
  WalkingSkeletonApiResponse,
  WalkingSkeletonSuccess,
} from "@/lib/walking-skeleton/types";

type LoadState =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "success"; data: WalkingSkeletonSuccess }
  | { kind: "error"; message: string };

function shortId(value: string): string {
  return `${value.slice(0, 8)}…${value.slice(-4)}`;
}

export function WalkingSkeletonClient() {
  const [state, setState] = useState<LoadState>({ kind: "idle" });

  async function runTrace() {
    setState({ kind: "loading" });

    try {
      const response = await fetch("/api/walking-skeleton", {
        method: "GET",
        cache: "no-store",
        headers: { Accept: "application/json" },
      });
      const body = (await response.json()) as WalkingSkeletonApiResponse;

      if (!response.ok || !body.ok) {
        const message = !body.ok
          ? `${body.error} (${body.stage})`
          : "The trace returned an unexpected response.";
        setState({ kind: "error", message });
        return;
      }

      setState({ kind: "success", data: body });
    } catch {
      setState({
        kind: "error",
        message: "The public API could not be reached. Please try again.",
      });
    }
  }

  const data = state.kind === "success" ? state.data : undefined;

  return (
    <div className="trace-console">
      <div className="trace-control">
        <div>
          <span className="status-dot" data-state={state.kind} />
          <span className="status-label">
            {state.kind === "idle" && "READY TO TRACE"}
            {state.kind === "loading" && "TRACE IN PROGRESS"}
            {state.kind === "success" &&
              state.data.mode === "bedrock" &&
              "LIVE END-TO-END PATH CONFIRMED"}
            {state.kind === "success" &&
              state.data.mode === "pregenerated" &&
              "PRE-GENERATED DEMO PATH CONFIRMED"}
            {state.kind === "success" &&
              state.data.mode === "fallback" &&
              "MEMORY PATH CONFIRMED · BEDROCK DEGRADED"}
            {state.kind === "error" && "TRACE STOPPED"}
          </span>
        </div>
        <button
          type="button"
          onClick={runTrace}
          disabled={state.kind === "loading"}
        >
          {state.kind === "loading" ? "Tracing…" : "Run live trace"}
          <span aria-hidden="true">↗</span>
        </button>
      </div>

      <div className="trace-body">
        <div className="response-panel" aria-live="polite">
          {state.kind === "idle" && (
            <div className="placeholder">
              <span>村人の記憶を呼び出す</span>
              <p>
                Run the trace to retrieve the fixed memory and ask the villager
                to recall it.
              </p>
            </div>
          )}

          {state.kind === "loading" && (
            <div className="placeholder">
              <span lang="ja">記憶をたどっています…</span>
              <p>Crossing the server, memory, and model boundaries.</p>
            </div>
          )}

          {state.kind === "error" && (
            <div className="error-card">
              <span>THE TRACE FAILED CLOSED</span>
              <p>{state.message}</p>
              <small>
                Managed MCP failures never fall back to a direct database read.
              </small>
            </div>
          )}

          {data && (
            <div className="answer-card">
              <div className="speaker">
                <span aria-hidden="true">ゲ</span>
                <div>
                  <strong>Gen, well keeper</strong>
                  <small>
                    {data.mode === "bedrock"
                      ? "Grounded by Amazon Nova Lite"
                      : data.mode === "pregenerated"
                        ? "Pre-generated by Nova Lite"
                        : "Deterministic model fallback"}
                  </small>
                </div>
              </div>
              <blockquote lang="ja">{data.npcLineJa}</blockquote>
              <p className="translation">{data.sourceMessageEn}</p>
              <dl>
                <div>
                  <dt>WORLD</dt>
                  <dd title={data.worldId}>{shortId(data.worldId)}</dd>
                </div>
                <div>
                  <dt>PROBE</dt>
                  <dd>{data.probeKey}</dd>
                </div>
                <div>
                  <dt>MODE</dt>
                  <dd>{data.mode}</dd>
                </div>
              </dl>
            </div>
          )}
        </div>

        <ol className="stage-list" aria-label="Trace stages">
          {(data?.path ?? [
            {
              stage: "browser",
              status: "ok" as const,
              detail: "Waiting for a live request.",
            },
            {
              stage: "amplify",
              status: "ok" as const,
              detail: "Waiting for a live request.",
            },
            {
              stage: "managed-mcp",
              status: "ok" as const,
              detail: "Waiting for a live request.",
            },
            {
              stage: "cockroachdb",
              status: "ok" as const,
              detail: "Waiting for a live request.",
            },
            {
              stage: "bedrock",
              status: "ok" as const,
              detail: "Waiting for a live request.",
            },
          ]).map((stage, index) => (
            <li key={stage.stage} data-active={Boolean(data)}>
              <span className="stage-number">
                {String(index + 1).padStart(2, "0")}
              </span>
              <div>
                <strong>{stage.stage.replace("-", " ")}</strong>
                <small>{stage.detail}</small>
              </div>
              <span
                className="stage-state"
                data-status={data ? stage.status : "waiting"}
              >
                {data ? stage.status : "waiting"}
              </span>
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
}
