/**
 * Split a SQL script into individual statements.
 *
 * Deliberately small: the scripts this parses are generated by
 * scripts/embed_seed.py and hand-written schema DDL, neither of which uses
 * dollar-quoting or nested comment blocks. It only needs to know that a
 * semicolon inside a string literal is not a statement boundary, and that a
 * doubled apostrophe is an escaped one rather than the end of the literal.
 */
export function statements(sql) {
  const out = [];
  let current = "";
  let inString = false;

  for (let i = 0; i < sql.length; i += 1) {
    const char = sql[i];

    if (!inString && char === "-" && sql[i + 1] === "-") {
      while (i < sql.length && sql[i] !== "\n") i += 1;
      current += "\n";
      continue;
    }

    if (char === "'") {
      if (inString && sql[i + 1] === "'") {
        current += "''";
        i += 1;
        continue;
      }
      inString = !inString;
      current += char;
      continue;
    }

    if (char === ";" && !inString) {
      const trimmed = current.trim();
      if (trimmed) out.push(trimmed);
      current = "";
      continue;
    }

    current += char;
  }

  const tail = current.trim();
  if (tail) out.push(tail);
  return out;
}
